Let's see the advantages of Numpy array over Python ordinary array.

## Array Conversion

In [1]:
import numpy as np

In [2]:
arr = [1, 2, 3, 4]
np_arr = np.array(arr)

In [3]:
type(np_arr)

numpy.ndarray

In [4]:
arr_2 = [1, 2, 4, '5']
np_arr_2 = np.array(arr_2)

In [5]:
np_arr_2

array(['1', '2', '4', '5'], dtype='<U21')

Be careful that Numpy variables are copied by reference. So this is what will happen.

In [6]:
np_arr = np.array([1, 2, 3, 4])
np_arr_2 = np_arr

In [7]:
np_arr[0] = 100
np_arr

array([100,   2,   3,   4])

In [8]:
np_arr_2

array([100,   2,   3,   4])

To copy elements by value, use copy() instead.

In [9]:
np_arr = np.array([2, 4, 6, 8])
np_arr_2 = np_arr.copy()

In [10]:
np_arr[0] = 10
np_arr

array([10,  4,  6,  8])

In [11]:
np_arr_2

array([2, 4, 6, 8])

## Array Operations

With ordinary array, we can't do this.

In [12]:
arr += 1

TypeError: 'int' object is not iterable

But with numpy array, we can.

In [13]:
np_arr += 1

In [14]:
np_arr

array([11,  5,  7,  9])

Operation between Numpy array and regular array is also possible.

In [15]:
np_arr + arr

array([12,  7, 10, 13])

In [16]:
np_arr * arr

array([11, 10, 21, 36])

In [17]:
np_arr.fill(10)
np_arr

array([10, 10, 10, 10])

## Logic Operations

Logical operation that returns array of boolean only works between array with same length.

In [18]:
a_1 = np.array([1, 3, 4, 5, 6])
a_2 = np.array([2, 3, 4, 1, 7])

In [19]:
a_1 == a_2

array([False,  True,  True, False, False])

In [20]:
a_1 != a_2

array([ True, False, False,  True,  True])

In [21]:
a_1 >= a_2

array([False,  True,  True,  True, False])

In [22]:
a_1 < a_2

array([ True, False, False, False,  True])

In [23]:
a_3 = np.array([1, 3, 5])
a_1 == a_3

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  


False

## Size and dimension functions

In [24]:
np_arr.size

4

In [25]:
np_arr.shape

(4,)

In [26]:
np_arr.ndim

1

Consider we construct a matrix with Numpy.

In [27]:
mat = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
mat.size #number of elements

9

In [29]:
mat.shape #number of rows and columns

(3, 3)

In [30]:
mat.ndim

2

Overall, indexing function in Numpy is similar with indexing in Python array.

In [31]:
mat[0,0]

1

In [32]:
mat[0,1] = 12
mat

array([[ 1, 12,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [33]:
mat[:, 2] #get column with index 2

array([3, 6, 9])

In [34]:
mat[0, 0:2] #slice first row

array([ 1, 12])

## Type Conversion

In [35]:
arr = np.array([1, 2, 3, 4, 5], dtype = np.float32)
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [36]:
arr_2 = np.array([1, 2, '3', 4])
arr_2

array(['1', '2', '3', '4'], dtype='<U21')

How if we want to keep each type unchanged?

In [37]:
arr_2 = np.array([1, 2, '3', 4], dtype = object)
arr_2

array([1, 2, '3', 4], dtype=object)

Each element behaves according to each of its type.

In [38]:
arr_2 *= 3
arr_2

array([3, 6, '333', 12], dtype=object)