# Calculations

In [1]:
import numpy as np

## Basic Calculations

In [2]:
arr = np.array([[4, 6, 1],
               [5, -1, 2],
               [9, 3, 11]])
arr

array([[ 4,  6,  1],
       [ 5, -1,  2],
       [ 9,  3, 11]])

In [3]:
arr.sum()

40

In [4]:
arr.prod()

-71280

In [5]:
arr.min()

-1

In [6]:
arr.max()

11

In [7]:
arr.argmin() #index of minimum value

4

In [8]:
arr.argmax() #index of maximum value

8

In [9]:
arr.mean()

4.444444444444445

In [10]:
arr.std()

3.593547028621384

In [11]:
arr.var()

12.913580246913579

## Calculation on Axis

In [12]:
arr

array([[ 4,  6,  1],
       [ 5, -1,  2],
       [ 9,  3, 11]])

In [13]:
arr.sum(axis = 0) #for vertical axis

array([18,  8, 14])

In [14]:
arr.sum(axis = 1)

array([11,  6, 23])

In [15]:
arr.prod(axis = 0)

array([180, -18,  22])

In [16]:
arr.prod(axis = 1)

array([ 24, -10, 297])

In [17]:
arr.min(axis = 1)

array([ 1, -1,  3])

In [18]:
arr.argmin(axis = 1)

array([2, 1, 1])

In [19]:
arr.mean(axis = 0)

array([6.        , 2.66666667, 4.66666667])

In [20]:
arr.std(axis = 0)

array([2.1602469 , 2.86744176, 4.49691252])

In [21]:
arr.var(axis = 0)

array([ 4.66666667,  8.22222222, 20.22222222])

## Value manipulation

In [22]:
arr_2 = np.random.rand(10) * 5
arr_2

array([0.99431277, 2.38515691, 1.72063567, 0.16748674, 3.9407661 ,
       0.21886277, 1.50738451, 3.96634966, 3.45375505, 4.88999785])

In [23]:
arr_2.round()

array([1., 2., 2., 0., 4., 0., 2., 4., 3., 5.])

In [24]:
arr_2.round(decimals = 2)

array([0.99, 2.39, 1.72, 0.17, 3.94, 0.22, 1.51, 3.97, 3.45, 4.89])

In [25]:
np.floor(arr_2)

array([0., 2., 1., 0., 3., 0., 1., 3., 3., 4.])

In [26]:
arr_2.clip(2, 4) #convert each value into clipped min and max value of array.

array([2.        , 2.38515691, 2.        , 2.        , 3.9407661 ,
       2.        , 2.        , 3.96634966, 3.45375505, 4.        ])

In [27]:
np.sort(arr_2)

array([0.16748674, 0.21886277, 0.99431277, 1.50738451, 1.72063567,
       2.38515691, 3.45375505, 3.9407661 , 3.96634966, 4.88999785])

In [28]:
arr_2

array([0.99431277, 2.38515691, 1.72063567, 0.16748674, 3.9407661 ,
       0.21886277, 1.50738451, 3.96634966, 3.45375505, 4.88999785])

In [29]:
arr_2.sort()
arr_2

array([0.16748674, 0.21886277, 0.99431277, 1.50738451, 1.72063567,
       2.38515691, 3.45375505, 3.9407661 , 3.96634966, 4.88999785])

In [30]:
np.argsort(arr) #order of each elements

array([[2, 0, 1],
       [1, 2, 0],
       [1, 0, 2]])

In [31]:
arr_3 = np.array([2, 3, 4]) #where to insert them to keep the array ordered?
np.searchsorted(arr_2, arr_3)

array([5, 6, 9])