In [1]:
import numpy as np

# Reshape

In [2]:
arr = np.arange(10)
arr.shape

(10,)

In [3]:
arr.shape = 2, 5
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
arr.shape = 3, 4
arr

ValueError: cannot reshape array of size 10 into shape (3,4)

In [5]:
arr.reshape(1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Newaxis and Squeeze

In [6]:
arr_2 = arr[np.newaxis, :]
arr_2

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [7]:
arr_2.shape

(1, 2, 5)

In [8]:
arr_2 = arr[:, np.newaxis]
arr_2

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [9]:
arr_2.shape

(2, 1, 5)

In [10]:
arr.shape = 10
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr.shape

(10,)

In [12]:
arr_2 = arr[:, np.newaxis, np.newaxis]
arr_2.shape

(10, 1, 1)

In [13]:
arr_2 = arr_2.squeeze()
arr_2.shape

(10,)

# Transpose

In [14]:
arr_2 = arr_2.reshape(2, 5)
arr_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
arr_2.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [16]:
arr_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

# Array Concatenation

In [17]:
arr = np.array([[1, 2],
               [3, 4]])
arr_2 = np.array([[7, 8],
                 [12, 13]])
arr_3 = np.concatenate((arr, arr_2))
arr_3

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [12, 13]])

In [18]:
arr_3 = np.concatenate((arr, arr_2), axis = 1)
arr_3

array([[ 1,  2,  7,  8],
       [ 3,  4, 12, 13]])

In [19]:
np.vstack((arr, arr_2)) #concatenate vertically

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [12, 13]])

In [20]:
np.hstack((arr, arr_2)) #concatenate horizontally

array([[ 1,  2,  7,  8],
       [ 3,  4, 12, 13]])

# Flatten and Ravel

In [21]:
arr_3.flatten()

array([ 1,  2,  7,  8,  3,  4, 12, 13])

In [22]:
arr_3

array([[ 1,  2,  7,  8],
       [ 3,  4, 12, 13]])

In [23]:
arr_3.ravel()

array([ 1,  2,  7,  8,  3,  4, 12, 13])

In [24]:
arr_3

array([[ 1,  2,  7,  8],
       [ 3,  4, 12, 13]])