# Arange and Linspace

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [4]:
np.arange(0, 10, 3, dtype = np.float32)

array([0., 3., 6., 9.], dtype=float32)

In [5]:
np.linspace(0, 10, 30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

Short expression of arange, to create array as row and column respectively.

In [6]:
np.r_[0:10:3] #arange as row

array([0, 3, 6, 9])

In [7]:
np.c_[0:10:3] #arange as column

array([[0],
       [3],
       [6],
       [9]])

# Meshgrid

Return coordinate matrices from coordinate vectors.

In [8]:
arr_2 = np.linspace(0, 2, 5)
arr_2

array([0. , 0.5, 1. , 1.5, 2. ])

In [9]:
arr_3 = arr_2.copy()

In [10]:
x, y = np.meshgrid(arr_2, arr_3)
x

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 0.5, 1. , 1.5, 2. ],
       [0. , 0.5, 1. , 1.5, 2. ],
       [0. , 0.5, 1. , 1.5, 2. ],
       [0. , 0.5, 1. , 1.5, 2. ]])

In [11]:
y

array([[0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.5],
       [2. , 2. , 2. , 2. , 2. ]])

# Zeros and Ones Array

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones((4, 4), dtype = np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

Create zeros or ones array with dimension of given array.

In [16]:
numbers = [1, 2, 3, 4, 5]

In [17]:
np.zeros_like(numbers)

array([0, 0, 0, 0, 0])

In [18]:
np.ones_like(numbers)

array([1, 1, 1, 1, 1])

# Identity Matrix

In [19]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.identity(5, dtype = np.int32)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)