In [1]:
import numpy as np

# Basic Random Function

In [2]:
np.random.rand(10)

array([0.77089114, 0.06353403, 0.38327013, 0.64806054, 0.97345129,
       0.02859773, 0.37636595, 0.27838539, 0.28167103, 0.57160723])

In [3]:
np.random.rand(4, 3)

array([[0.95432738, 0.47706687, 0.7293539 ],
       [0.14353351, 0.40756331, 0.04482578],
       [0.08379634, 0.15354142, 0.03849727],
       [0.76669126, 0.20582286, 0.42101014]])

In [4]:
np.set_printoptions(precision = 3)

In [5]:
np.random.rand(2, 2)

array([[0.166, 0.979],
       [0.826, 0.762]])

## Random Function with Bounded Integer

In [6]:
np.random.randint(30, size = (5, 5))

array([[27, 26, 17, 11, 13],
       [14, 26,  0, 19, 29],
       [22, 14, 15, 12,  7],
       [21,  0, 19, 28, 24],
       [ 5, 18, 13, 28, 17]])

In [7]:
np.random.randint(5, 10, 9)

array([6, 9, 9, 9, 6, 6, 9, 8, 9])

# Shuffle

In [8]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
np.random.shuffle(arr)
arr

array([ 5,  8,  3, 27, 25, 14, 29,  2, 17, 21, 18, 22,  0,  6,  1,  7, 23,
       11, 24, 10, 12, 15,  9, 13, 19, 16, 20, 26, 28,  4])

# Random Seed

In [10]:
np.random.rand(3,3)

array([[0.866, 0.508, 0.794],
       [0.745, 0.364, 0.624],
       [0.032, 0.354, 0.464]])

Set a random state, next run random instruction may give unchanged numbers.

In [13]:
np.random.seed(1)

In [14]:
np.random.rand(3,3)

array([[4.170e-01, 7.203e-01, 1.144e-04],
       [3.023e-01, 1.468e-01, 9.234e-02],
       [1.863e-01, 3.456e-01, 3.968e-01]])

Try rerun the seed() and rand() above several times to see the effect.