In [1]:
import numpy as np

### Invert two rows in a matrix.

In [2]:
mat = np.arange(20).reshape(4, 5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
mat[[0,2]] = mat[[2,0]]
mat

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

### Find n highest numbers in an array.

In [4]:
arr = np.arange(200)
np.random.shuffle(arr)
arr

array([ 31, 149,  12,  36, 116,  71,  84,  66, 137,  22, 173,  72, 190,
       146, 179,  87, 119, 144,  45,   9,   2,  76, 100,  11, 114,  80,
        89, 131, 126, 187, 107, 148,  16,  65, 138, 140,  50,   6, 129,
       165, 141,  75, 118, 139,  53,  47,  21, 196, 180,  88, 111,  70,
        83,  91,   4, 158, 147,  39, 163, 145, 194, 157,  44, 156, 171,
       125,  67, 197, 109, 112,  90,  27, 178,  29, 172,  68,  55, 150,
        46,  79,  42,  49, 174, 186,  20,   0, 127, 175, 185,  54,  25,
        59,  35, 170, 133, 177,  43, 152,  61, 113, 128, 115, 162, 122,
       103, 164, 183, 195,  92,  40, 108, 101, 132, 124,  94, 181,  34,
        19,  15, 105,  33,  69,  64, 123, 166,  51, 155,  10,  86, 142,
       193,  82,  78, 189, 102, 184, 136,  23,  24,  30, 160,  57,  58,
       151,  60,  77, 153, 159,  63, 117, 191,  74,  85,  41,  32,  14,
       188,  28,   3, 110, 168,  38,  48, 182, 120, 143, 198,  93, 169,
       135,   1,  18,  96, 192,  37,   5,  52, 106,   7, 199,  7

In [5]:
n = 5
arr[np.argpartition(-arr, n)][:n]

array([197, 198, 196, 199, 195])

### Find size of each array element.

In [6]:
arr.itemsize

8

### Create an array with outer frame made of zero.

In [7]:
ones = np.ones((4, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
ones = np.pad(ones, pad_width = 1, mode = "constant", constant_values = 0)
ones

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

### Print every date in December 2018.

In [9]:
np.arange("2018-12","2019-01", dtype="datetime64[D]")

array(['2018-12-01', '2018-12-02', '2018-12-03', '2018-12-04',
       '2018-12-05', '2018-12-06', '2018-12-07', '2018-12-08',
       '2018-12-09', '2018-12-10', '2018-12-11', '2018-12-12',
       '2018-12-13', '2018-12-14', '2018-12-15', '2018-12-16',
       '2018-12-17', '2018-12-18', '2018-12-19', '2018-12-20',
       '2018-12-21', '2018-12-22', '2018-12-23', '2018-12-24',
       '2018-12-25', '2018-12-26', '2018-12-27', '2018-12-28',
       '2018-12-29', '2018-12-30', '2018-12-31'], dtype='datetime64[D]')

### Modify write access on variable.

In [10]:
m_i = np.identity(5)
m_i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
m_i.flags.writeable = False

In [12]:
m_i[0][2]

0.0

In [13]:
m_i[0][2] = 99

ValueError: assignment destination is read-only